"""Add url column to job_post table

Revision ID: 37d8d09409be
Revises: eff799bde6a3
Create Date: 2025-10-07 08:47:15.534708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37d8d09409be"
down_revision: Union[str, Sequence[str], None] = "eff799bde6a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_post", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_post", "url")
    # ### end Alembic commands ###
