"""Add summarized_job table

Revision ID: e598cd96fac0
Revises: 37d8d09409be
Create Date: 2025-10-13 09:29:53.481410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e598cd96fac0"
down_revision: Union[str, Sequence[str], None] = "37d8d09409be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summarized_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_post_id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("technical_skills", sa.Text(), nullable=False),
        sa.Column("seniority_level", sa.String(), nullable=False),
        sa.Column("estimated_salary_min", sa.Integer(), nullable=True),
        sa.Column("estimated_salary_max", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_post_id"],
            ["job_post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summarized_job")
    # ### end Alembic commands ###
