"""Add job_page table

Revision ID: eff799bde6a3
Revises: 59ffee20774c
Create Date: 2025-10-07 08:20:40.186790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eff799bde6a3"
down_revision: Union[str, Sequence[str], None] = "59ffee20774c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_page",
        sa.Column("page_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("page_html", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("page_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_page")
    # ### end Alembic commands ###
